name: CI of semantyca
    
on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ./gradlew libertyPackage
    - run: ./gradlew libertyRun --no-daemon


